# Generated by Django 5.0.4 on 2024-09-25 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria_producto', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria_producto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='categoria_producto.categoria_producto', verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
