# Generated by Django 5.0.4 on 2024-09-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_medida', models.CharField(max_length=100, verbose_name='tipo_medida')),
                ('description', models.TextField(max_length=200, verbose_name='descripcion')),
            ],
        ),
    ]
