# Generated by Django 5.0.4 on 2024-09-21 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria_insumo', '0001_initial'),
        ('medida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('categoria_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria_insumo.categoria_insumo', verbose_name='Categoria')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medida.medida', verbose_name='Medida')),
            ],
        ),
    ]
